services:
  auth-db:
    image: postgres:16
    container_name: auth-db
    environment:
      POSTGRES_DB: auth
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_pass
    ports:
      - "5432:5432"
    volumes:
      - auth_pgdata:/var/lib/postgresql/data
  catalog-db:
    image: postgres:16
    container_name: catalog-db
    environment:
      POSTGRES_DB: catalog
      POSTGRES_USER: catalog_user
      POSTGRES_PASSWORD: catalog_pass
    ports:
      - "5433:5432"
    volumes:
      - catalog_pgdata:/var/lib/postgresql/data
      
  booking-db:
    image: postgres:16
    container_name: booking-db
    environment:
      POSTGRES_DB: booking
      POSTGRES_USER: booking_user
      POSTGRES_PASSWORD: booking_pass
    ports:
      - "5434:5432"
    volumes:
      - booking_pgdata:/var/lib/postgresql/data

  log-db:
    image: postgres:16
    container_name: log-db
    environment:
      POSTGRES_DB: logs
      POSTGRES_USER: log_user
      POSTGRES_PASSWORD: log_pass
    ports:
      - "5435:5432"
    volumes:
      - log_pgdata:/var/lib/postgresql/data

      
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest



volumes:
  auth_pgdata:
  catalog_pgdata:
  booking_pgdata:
  log_pgdata:
